services:
  # Producer A (The 'Frontend')
  producer-a:
    build:
      context: ./producer
      dockerfile: Dockerfile
    container_name: producer-a
    ports:
      - "8081:8080"
    environment:
      - OTEL_SERVICE_NAME=producer-a
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://alloy-edge:4317
      - DOWNSTREAM_URLS=http://producer-b:8080
      - ERROR_RATE=5
      - SLOW_RATE=10
    networks:
      - app-net

  # Producer B (The 'Backend')
  producer-b:
    build:
      context: ./producer
      dockerfile: Dockerfile
    container_name: producer-b
    ports:
      - "8082:8080"
    environment:
      - OTEL_SERVICE_NAME=producer-b
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://alloy-edge:4317
      - TRAFFIC_GEN_ENABLED=false # B only reacts to A
    networks:
      - app-net

  victoriametrics:
    build:
      context: ./victoriametrics
    ports:
      - "8428:8428"
    networks:
      - storage-net

  loki:
    build:
      context: ./loki
    ports:
      - "3100:3100"
    networks:
      - storage-net

  tempo:
    build:
      context: ./tempo
    ports:
      - "3200:3200"
      - "4317:4317" # OTLP gRPC
      - "4318:4318" # OTLP HTTP
    networks:
      - storage-net

  grafana:
    build:
      context: ./grafana
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    depends_on:
      - victoriametrics
      - loki
      - tempo
    networks:
      - storage-net

networks:
  app-net:
    driver: bridge
  pipeline-net:
    driver: bridge
  storage-net:
    driver: bridge
